### PR TITLE
autotools: skip tests requiring static lib if `--disable-static`

### LINKED ISSUE #1056: `make check` fails with `--disable-static`
**Describe the bug**

`make check` fails with `--disable-static`.

**To Reproduce**

```
./configure --prefix=/usr --disable-static && make && make check
```

It produces:

```
/usr/bin/ld: test_auth_keyboard_info_request.o: in function `main':
test_auth_keyboard_info_request.c:(.text.startup+0xec): undefined reference to `userauth_keyboard_interactive_decode_info_request'
/usr/bin/ld: test_auth_keyboard_info_request.c:(.text.startup+0x201): undefined reference to `userauth_keyboard_interactive_decode_info_request'
collect2: error: ld returned 1 exit status
```

**Expected behavior**

Test succeeds.

**Version:**
 - OS and version: Linux (Linux From Scratch)
 - libssh2 version: 1.11.0
 - crypto backend and version: OpenSSL

**Additional context**

It looks like the reason is `userauth_keyboard_interactive_decode_info_request` not exported in the shared library because we are linking libssh2.so with `-export-symbols-regex '^libssh2_.*'`.

### PR DESCRIPTION
**Pull request by xry111**
Regression from 83853f8aea0e2f739cacd491632eb7fd3d03ad2d #663
Fixes #1056

### CODE REVIEW

**Comment by vszakats** [comment]
Thank you! Merged now.
