### ISSUE TITLE
undefined reference to `DSA_set0_key'

### ISSUE THREAD

**Issue by dvdobrovolskiy** [libssh2/libssh2#153]
make[1]: Entering directory `/home/install/libssh2-1.8.0/tests'
  CCLD     ssh2
../src/.libs/libssh2.so: undefined reference to `DSA_set0_key'
../src/.libs/libssh2.so: undefined reference to `DSA_get0_key'
../src/.libs/libssh2.so: undefined reference to `RSA_get0_key'
../src/.libs/libssh2.so: undefined reference to `DSA_get0_pqg'
../src/.libs/libssh2.so: undefined reference to `RSA_set0_key'
../src/.libs/libssh2.so: undefined reference to `DSA_set0_pqg'
../src/.libs/libssh2.so: undefined reference to `EVP_CIPHER_CTX_reset'
../src/.libs/libssh2.so: undefined reference to `EVP_MD_CTX_new'
../src/.libs/libssh2.so: undefined reference to `HMAC_CTX_free'
../src/.libs/libssh2.so: undefined reference to `OPENSSL_init_crypto'
../src/.libs/libssh2.so: undefined reference to `DSA_SIG_get0'
../src/.libs/libssh2.so: undefined reference to `RSA_set0_crt_params'
../src/.libs/libssh2.so: undefined reference to `EVP_MD_CTX_free'
../src/.libs/libssh2.so: undefined reference to `DSA_SIG_set0'
../src/.libs/libssh2.so: undefined reference to `HMAC_CTX_new'
../src/.libs/libssh2.so: undefined reference to `RSA_set0_factors'
collect2: error: ld returned 1 exit status
make[1]: *** [ssh2] Error 1
make[1]: Leaving directory `/home/install/libssh2-1.8.0/tests'
make: *** [all-recursive] Error 1

Centos 7.2
Openssl 1.0.1u

**Comment by willco007** [comment]
It appears you're attempting to build with openssl 1.0.x while HAVE_OPAQUE_STRUCTS is being set to 1 in openssl.h for some reason.
